### PR TITLE
OCaml 4.11 support

### PR DESCRIPTION
**Pull request by kit-ty-kate**
Relies on https://github.com/ocaml-ppx/ppx_tools/pull/82

### CODE REVIEW

**Comment by thierry-martinez** [comment]
Thank you, @kit-ty-kate ! There is a long standing pull request https://github.com/ocaml-ppx/ppx_deriving/pull/210 , which is about to be accepted (I think!), and which migrates `ppx_deriving` to `ppxlib`, dropping the dependency to `ppx_tools`. However, the compatibility with OCaml 4.11.0 has to be checked.

**Comment by kit-ty-kate** [comment]
I don't think #210 changes anything to the core of this PR. I'll happily rebase it if it does though.
By `relies on the ppx_tools PR` I meant more that currently it requires that PR to be merged and released first to be able to compile it in CI.

For the moment this PR is a draft as no alpha/beta release of OCaml 4.11 is available yet, so maybe the API can still change.

**Comment by kit-ty-kate** [comment]
The switch to ppxlib seems to mean this PR is no longer needed. Maybe a the CI entry can still be added?

**Comment by gasche** [comment]
I would be happy to merge the CI support, but for now the 4.11 CI seems to be failing. Do we want to understand why before merging? (I am worried about the "noise" aspect of every CI showing red from the big picture before this is fixed.)

**Comment by thierry-martinez** [comment]
CI is green now! Merged. Thank you very much!

**Pull request merged**
